version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.17.0

    steps:
      - checkout

      - run:
          name: Uninstall dependencies
          command: npm uninstall cypress

      - run:
          name: Install dependencies
          command: npm install cypress --save-dev

      - run:
          name: Run Cypress tests
          command: npm run test:login   # Adjust this to your Cypress test run command

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - circelci # Change this to your main branch name
