version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.17.0

    steps:
      - checkout

      - run:
          name: Install Xvfb
          command: sudo apt-get update && sudo apt-get install -y xvfb

      - run:
          name: Uninstall dependencies
          command: npm uninstall cypress

      - run:
          name: Install dependencies
          command: npm install cypress --save-dev

      - run:
          name: Run Cypress tests with Xvfb
          command: xvfb-run npm run test:login   # Run Cypress with Xvfb

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - circelci # Change this to your main branch name
