version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:18.17.0 # Use the Node.js version you need for your project
    working_directory: ~/repo

jobs:
  build:
    executor: node
    steps:
      - checkout
      
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Uninstall Cypress if installed
          command: npm uninstall cypress

      - run:
          name: Install dependencies
          command: npm install cypress --save-dev

      - run:
          name: Make cypress-parallel executable
          command: chmod +x node_modules/.bin/cypress-parallel

      - run:
          name: Run Cypress tests
          command: npm run test:login

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - store_artifacts:
          path: cypress/videos
          destination: videos
          
      - store_artifacts:
          path: cypress/screenshots
          destination: screenshots

      - store_test_results:
          path: cypress/results

workflows:
  version: 2
  test:
    jobs:
      - build
