version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:14.17.0-buster
    working_directory: ~/repo

jobs:
  install_dependencies:
    executor: node
    steps:
      - checkout
      - run:
          name: Update system packages
          command: |
            sudo apt-get update
            sudo apt-get upgrade -y
      - run:
          name: Install system dependencies
          command: |
            sudo apt-get install -y libgtk-3-0 libxss1 libasound2 libnss3
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install Node.js dependencies
          command: npm install
      - run:
          name: Install Cypress
          command: npm install cypress --save-dev
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  run_tests:
    executor: node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run Cypress tests
          command: npx cypress run
      - store_artifacts:
          path: cypress/videos
          destination: videos
      - store_artifacts:
          path: cypress/screenshots
          destination: screenshots
      - store_test_results:
          path: cypress/results

workflows:
  version: 2
  test:
    jobs:
      - install_dependencies
      - run_tests:
          requires:
            - install_dependencies
