name: Cypress Tests

on:
  push:
    branches:
      - master # Change this to your main branch name
jobs:
  build:
    runs-on: ubuntu-latest
    

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.17.0 # Use the Node.js version you need for your project

      - name: unInstall dependencies
        run: npm uninstall cypress

      - name: Install dependencies
        run: npm install cypress --save-dev

      - name: Make cypress-parallel executable
        run: chmod +x node_modules/.bin/cypress-parallel

      - name: Run Cypress tests
        run: npm run test:prd   # Adjust this to your Cypress test run command

      - name: Uploading artifact
        run: actions/upload-artifact@v2
        if: always()
        with: 
          name: cypress-execution-report
          path: cypress/reports/html
          retention-day: 30
        name: slack Notification
        uses: stCamp/action-slack-notify@v2
        env:
           SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
           SLACK_USERNAME: anish.kumar
           SLACK_TITLE: AAPI Test Report
           SLACK_Message: "New Report Genrated :rocket:"
           SLACK_COLOR: ${{ job.status}}

          
