name: Cypress Tests

on:
  push:
    branches:
      - master # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.17.0 # Use the Node.js version you need for your project

      - name: Install dependencies
        run: npm install cypress --save-dev
        
      - name: Change permission
        run: $ chmod +x script.sh
        
      - name: Run Cypress tests
        run: npm run test:smoke # Adjust this to your Cypress test run command
