name: Cypress Tests

on:
  push:
    branches:
      - master # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.17.0' # Use the Node.js version you need for your project

      - name: Uninstall dependencies
        run: npm uninstall cypress

      - name: Install dependencies
        run: npm install cypress --save-dev

      - name: Make cypress-parallel executable
        run: chmod +x node_modules/.bin/cypress-parallel

      - name: Run Cypress tests
        run: npm run test:prd   # Adjust this to your Cypress test run command

      - name: Uploading artifact
        uses: actions/upload-artifact@v2
        if: always() # This ensures that artifacts are uploaded regardless of the previous steps' success or failure
        with: 
          name: cypress-execution-report
          path: cypress/reports/html
          retention-days: 30 # Note: Corrected from 'retention-day' to 'retention-days'

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        if: always() # Send a notification regardless of job success or failure
        env:
          SLACK_CHANNEL: cb-automation-results
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: 'Himanshu Sharma'
          SLACK_TITLE: 'API Test Report'
          SLACK_MESSAGE: 'New Report Generated :rocket:'
          SLACK_COLOR: ${{ job.status }}
