name: Cypress Tests

on:
  push:
    branches:
      - master # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.17.0 # Use the Node.js version you need for your project

      - name: Uninstall dependencies
        run: npm uninstall cypress

      - name: Install dependencies
        run: npm install cypress --save-dev

      - name: Make cypress-parallel executable
        run: chmod +x node_modules/.bin/cypress-parallel

      - name: Run Cypress tests
        run: npm run test:prd   # Adjust this to your Cypress test run command

      - name: Notify Slack
        uses: rtCamp/action-slack-notify@v2
        env:
           SLACK_CHANNEL: 'automation-tests-results'  # Specify your Slack channel here
           SLACK_COLOR: '#42e2f4'
           SLACK_MESSAGE: 'API TEST AUTOMATION JOB COMPLETED'
           SLACK_TITLE: 'Cypress Test Completion'
           SLACK_USERNAME: 'Mithilesh Tiwari'
           SLACK_WEBHOOK: 'https://hooks.slack.com/services/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9'
           SLACK_MENTIONS: 'UTYMMF2TU'# Ensure you have set this secret in your repo settings
        if: always() # This ensures the notification always sends, regardless of test results
  
