name: Cypress Tests

on:
  push:
    branches:
      - master # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.17.0 # Use the Node.js version you need for your project

      - name: Uninstall dependencies
        run: npm uninstall cypress

      - name: Install dependencies
        run: npm install cypress --save-dev

      - name: Make cypress-parallel executable
        run: chmod +x node_modules/.bin/cypress-parallel

      - name: Run Cypress tests
        run: npm run test:prd   # Adjust this to your Cypress test run command
      
      - name: Notify Slack
        if: always() # Ensures that the notification is sent regardless of the previous steps' success or failure
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: automation-tests-results # Channel ID or name
          SLACK_USERNAME: anish.kumar
          SLACK_COLOR: ${{ job.status }} # Color changes based on job status
          SLACK_MESSAGE: 'Cypress Test Results: ${{ job.status }}'
          SLACK_TITLE: 'Test Notification'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK}} # Ensure you've added your Webhook URL to your repository's secrets
