name: Cypress Tests

on:
  push:
    branches:
      - master # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.17.0' # Always quote version numbers to avoid YAML parsing issues

      - name: Uninstall dependencies
        run: npm uninstall cypress

      - name: Install dependencies
        run: npm install cypress --save-dev

      - name: Make cypress-parallel executable
        run: chmod +x node_modules/.bin/cypress-parallel

      - name: Run Cypress tests
        run: npm run test:prd   # Adjust this command to match your actual npm script for running tests

      - name: Uploading artifact
        uses: actions/upload-artifact@v2
        if: always() # Ensures artifacts are uploaded regardless of the job's success or failure
        with: 
          name: cypress-execution-report
          path: cypress/reports/html
          retention-days: 30 # Ensure this matches your requirements

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        if: always() # This will ensure the notification is sent regardless of the job's outcome
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: 'anish.kumar'
          SLACK_TITLE: 'API Test Report'
          SLACK_MESSAGE: 'New Report Generated :rocket:'
          SLACK_COLOR: ${{ job.status == 'success' ? 'good' : 'danger' }}  # Sets color based on job status
