name: Cypress Tests

on:
  push:
    branches:
      - master # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.17.0 # Use the Node.js version you need for your project

      - name: Uninstall dependencies
        run: npm uninstall cypress

      - name: Install dependencies
        run: npm install cypress --save-dev

      - name: Make cypress-parallel executable
        run: chmod +x node_modules/.bin/cypress-parallel

      - name: Run Cypress tests
        run: npm run test:prd   # Adjust this to your Cypress test run command

      - name: Notify Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: automation-tests-results # Channel to which the message will be sent
          SLACK_USERNAME: anish.kumar
          SLACK_COLOR: '#FF0000' # Color of the strip on message attachment
          SLACK_MESSAGE: 'Cypress Tests completed' # Custom message
          SLACK_TITLE: 'Test Notification'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }} # Ensure you have set this secret in your repo settings
        if: always() # This ensures the notification always sends, regardless of test results
  
